name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

  pull_request:
    paths:
      - 'backend/**'

jobs:
  backend:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Python Syntax Check
        run: |
          cd backend
          python -m py_compile app.py